// src/components/Graph.svelte
<script lang="ts">
	import { onDestroy, onMount } from 'svelte';
	import type { Unsubscriber } from 'svelte/store';
	import GraphController from "~/GraphController";

	let canvas_gl: HTMLCanvasElement;
	let canvas_2d: HTMLCanvasElement;

	export let controller: GraphController | undefined = undefined;


	onMount(() => {
		controller = new GraphController(canvas_gl, canvas_2d);
	});
</script>

<div class="graph">
	<canvas bind:this={canvas_2d}></canvas>
	<canvas bind:this={canvas_gl}></canvas>
</div>

<style lang="scss">
	.graph {
		width: 100%;
		height: 100%;

		display: grid;

		canvas {
			width: 100%;
			height: 100%;
			grid-area: 1 / 1;
		}
	}
</style>

// src/components/Graph.tsx
import GraphController from "GraphController";
import { Component, createEffect, onMount } from "solid-js";

export const Graph = (props: {expression: string}) => {
	let canvas_gl = <canvas></canvas> as HTMLCanvasElement;
	let canvas_2d = <canvas></canvas> as HTMLCanvasElement;

	let app: GraphController;

	onMount(() => {
		app = new GraphController(canvas_gl, canvas_2d);
	});

	createEffect(() => {
		app.setExpression(props.expression)
	});

	return <div class="graph-container">{canvas_2d} {canvas_gl}</div>
}
