// src/components/Layout.svelte
<script lang="ts">
	import { onMount } from "svelte";

	let container: HTMLDivElement;
	let handle: HTMLDivElement;

	let horizontal = window.innerWidth > window.innerHeight;
	let width = 0;
	let height = 0;
	let menuDesiredWidth = 500;
	let menuDesiredHeight = 500;
	let grabbing = false;

	function updateSize(x: number, y: number) {
		if (grabbing) {
			if (horizontal) {
				menuDesiredWidth = x - container.offsetLeft;
			} else {
				menuDesiredHeight = y - container.offsetTop;
			}
		}
	}

	onMount(() => {
		new ResizeObserver(els => {
			width = container.clientWidth;
			height = container.clientHeight;
			horizontal = width > height;
		}).observe(container);
	});

</script>

<div 
	bind:this={container} 
	class="container {horizontal ? "horizontal" : "vertical"}" 
	style="{horizontal ? `grid-template-columns: ${menuDesiredWidth}px 1fr` : `grid-template-rows: ${menuDesiredHeight}px 1fr`}"
	on:mousemove={e => updateSize(e.clientX, e.clientY)}
	on:touchmove={e => updateSize(e.touches[0].clientX, e.touches[0].clientY)}
	on:mouseup={e => grabbing = false}
	on:touchend={e => grabbing = false}
>
	<div class="menu">
		<slot name="menu"/>
		<div class="handle" bind:this={handle} on:mousedown={() => grabbing = true} on:touchstart={() => grabbing = true}></div>
	</div>
	<div class="main">
		<slot name="main"/>
	</div>
</div>

<style lang="scss">
	.container {
		width: 100%;
		height: 100%;
		display: grid;
		overflow: hidden;
		
		&.vertical {
			grid-template-columns: 1fr;
			grid-template-areas: "main" "menu";
			
			.handle {
				width: 100%;
				height: 10px;
				position: absolute;
				top: 0;
				left: 0;
				cursor: ns-resize;
			}
		}
	
		&.horizontal {
			grid-template-rows: 1fr;
			grid-template-areas: "menu main";

			.handle {
				width: 10px;
				height: 100%;
				position: absolute;
				top: 0;
				right: 0;
				cursor: ew-resize;
			}
		}

		.menu {
			grid-area: menu;
			position: relative;
			overflow: hidden;
			display: flex;
			box-shadow: rgb(0 0 0 / 90%) 0px 0px 20px;
		}
	
		.main {
			grid-area: main;
			overflow: hidden;
		}
	}


</style>

// src/components/Layout.tsx
import { createSignal, onMount } from "solid-js";
import { Graph } from "./Graph";

import { Menu } from "./Menu";

export const Layout = () => {
	const [preferedSettingsWidth, setPreferedSettingsWidth] = createSignal(400);
	const [preferedSettingsHeight, setPreferedSettingsHeight] = createSignal(400);
	const [windowSize, setWindowSize] = createSignal({width: 0, height: 0});
	const horizontalLayout = () => windowSize().width > windowSize().height;

	let grabbing = false;
	
	function onResize(){
		setWindowSize({width: window.innerWidth, height: window.innerHeight});
	}

	function move(x: number, y: number){
		if(!grabbing) return;

		if(horizontalLayout()) {
			setPreferedSettingsWidth(x);
		} else {
			setPreferedSettingsHeight(windowSize().height - y);
		}
	}

	onMount(() => {
		window.addEventListener("mousemove", e => move(e.clientX, e.clientY));
		window.addEventListener("touchmove", e => move(e.touches[0].clientX, e.touches[0].clientY));
		window.addEventListener("mouseup", e => grabbing = false);
		window.addEventListener("resize", onResize);

		onResize();
	});

	const menuWidth = () => Math.max(5, Math.min(windowSize().width*0.9, preferedSettingsWidth()));
	const menuHeight = () => Math.max(5, Math.min(windowSize().height*0.9, preferedSettingsHeight()));

	
	return <>
	<div class="container" style={horizontalLayout() ? `flex-direction: row-reverse` : `flex-direction: column`}>
		<main>
			<Graph expression="x^2 - y"/>
		</main>
		<div class="menu-container" style={
				horizontalLayout() 
				? `grid-row: 1; min-width: ${menuWidth()}px; max-width: ${menuWidth()}px;` 
				: `min-height: ${menuHeight()}px; max-height: ${menuHeight()}px;`
		}>
			<div 
				class={`handle ${horizontalLayout() ? "horizontal" : "vertical"}`} 
				onmousedown={() => grabbing = true} ontouchstart={() => grabbing = true}
			/>
			<div class="menu">
				<Menu />
			</div>
		</div>
	</div>
	</>
};
